spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_company
    username: roots
    password: roots
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
server:
  port: 8080
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
