spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_company
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
server:
  port: 8081
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
project:
  msg: hello
